services:
  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.5
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d