services:
  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: jeffersonlab/rfscopedb:1.0.0
    ports:
     - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "echo", "'use scope_waveforms'", "|", "mysql", "-u", "scope_rw", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 6
